name: build-img-ghrunner-test

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'pkg/integrations/github/*.go'
      - '.github/workflows/build-img-ghrunner-test.yaml'

jobs:
  build-mapt:
    name: build-mapt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
    - name: Install Podman (only for arm64)
      if: contains(matrix.os, 'arm')
      run: |
        sudo apt-get update -y
        sudo apt-get -y install podman
    - name: Set environment variables based on architecture
      run: |
        if [[ "${{ matrix.os }}" == *"arm"* ]]; then
          echo "ARCH_TYPE=arm64" >> $GITHUB_ENV
        else
          echo "ARCH_TYPE=amd64" >> $GITHUB_ENV
        fi
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image for PR
      if: ${{ github.event_name == 'pull_request' }}
      env:
        IMG: ghcr.io/redhat-developer/mapt-img-ghrunner-test:pr-${{ github.event.number }}
      shell: bash
      run: |
        make oci-build-${{ env.ARCH_TYPE }}
        make oci-save-${{ env.ARCH_TYPE }}
        echo ${IMG} > mapt-image

    - name: Create image metadata
      run: |
        echo ${{ github.event_name }} > mapt-event
        cat ./mapt-event

    - name: Upload crc-builder
      uses: actions/upload-artifact@v4
      with:
        name: mapt-${{ env.ARCH_TYPE }}
        path: mapt*

